/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#F9FAF8',
        'on-background': '#111c2c',
        surface: '#F9FAF8',
        'on-surface': '#111c2c',
        'on-surface-variant': '#46554E',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#F2F5F3',
        'surface-container': '#E8EFE9',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fa',
        primary: '#5B7563',
        'primary-dark': '#435c4b',
        'on-primary': '#ffffff',
        'primary-container': '#5B7563',
        'on-primary-container': '#ddfbe4',
        secondary: '#506356',
        'on-secondary': '#ffffff',
        'secondary-container': '#d3e8d7',
        'on-secondary-container': '#56695c',
        tertiary: '#495a4f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#617367',
        'on-tertiary-container': '#e4f8e9',
        outline: '#737973',
        'outline-variant': '#DCE3DD',
        // Critical terracotta override: NO raw red!
        error: '#A36B5E',
        'error-container': '#F7ECE9',
        'on-error': '#ffffff',
        'on-error-container': '#5C2B22',
        terracotta: '#A36B5E',
        'terracotta-container': '#F7ECE9',
        'terracotta-dark': '#855146',
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm: '0.5rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.375rem',
        'space-sm': '0.75rem',
        'space-md': '1.25rem',
        'space-lg': '2rem',
        'space-xl': '3.5rem',
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
        margin: '3rem',
        'margin-mobile': '1.25rem',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        headline: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        resting: '0px 4px 20px -4px rgba(36, 51, 44, 0.04), 0px 1px 3px 0px rgba(36, 51, 44, 0.02)',
        lift: '0px 8px 28px -6px rgba(36, 51, 44, 0.06), 0px 2px 6px 0px rgba(36, 51, 44, 0.03)',
        modal: '0px 16px 40px -8px rgba(36, 51, 44, 0.08), 0px 4px 12px 0px rgba(36, 51, 44, 0.02)',
      },
      animation: {
        'breathe': 'pulse-calm 8s ease-in-out infinite',
      },
      keyframes: {
        'pulse-calm': {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.85' },
          '50%': { transform: 'scale(1.08)', opacity: '0.45' },
        },
      },
    },
  },
  plugins: [],
};
