/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#FAF7F0',
        'on-background': '#292524',
        surface: '#FAF7F0',
        'on-surface': '#292524',
        'on-surface-variant': '#44403C',
        paper: '#FAF7F0',
        'paper-light': '#FFFDF9',
        'paper-card': '#FFFFFF',
        'paper-yellow': '#FEF9C3',
        'paper-mint': '#EBF5EE',
        'paper-rose': '#FCEBE6',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F5F1E6',
        'surface-container': '#EFE9D9',
        'surface-container-high': '#E5DECB',
        'surface-container-highest': '#DDD5BF',
        primary: '#5B7563',
        'primary-dark': '#435c4b',
        'on-primary': '#ffffff',
        'primary-container': '#5B7563',
        'on-primary-container': '#ddfbe4',
        secondary: '#506356',
        'on-secondary': '#ffffff',
        'secondary-container': '#d3e8d7',
        'on-secondary-container': '#56695c',
        tertiary: '#495a4f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#617367',
        'on-tertiary-container': '#e4f8e9',
        outline: '#445148',
        'outline-variant': '#D8D1BE',
        // Critical terracotta override: NO raw red!
        error: '#A36B5E',
        'error-container': '#F7ECE9',
        'on-error': '#ffffff',
        'on-error-container': '#5C2B22',
        terracotta: '#A36B5E',
        'terracotta-container': '#F7ECE9',
        'terracotta-dark': '#855146',
      },
      fontSize: {
        xs: ['0.875rem', { lineHeight: '1.25rem' }], // Safety floor: 14px minimum per spec
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm: '0.5rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.375rem',
        'space-sm': '0.75rem',
        'space-md': '1.25rem',
        'space-lg': '2rem',
        'space-xl': '3.5rem',
        gutter: '1.5rem',
        'gutter-mobile': '1rem',
        margin: '3rem',
        'margin-mobile': '1.25rem',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        handwriting: ['"Shantell Sans"', '"Patrick Hand"', 'cursive'],
        sketch: ['"Patrick Hand"', 'cursive'],
        display: ['"Shantell Sans"', 'sans-serif'],
        headline: ['"Shantell Sans"', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
      },
      boxShadow: {
        resting: '0px 4px 16px -2px rgba(41, 37, 36, 0.05), 0px 1px 3px 0px rgba(41, 37, 36, 0.03)',
        lift: '0px 8px 24px -4px rgba(41, 37, 36, 0.08), 0px 2px 6px 0px rgba(41, 37, 36, 0.04)',
        modal: '0px 20px 40px -10px rgba(41, 37, 36, 0.15), 0px 4px 12px 0px rgba(41, 37, 36, 0.05)',
        notebook: '2px 3px 0px 0px rgba(41, 37, 36, 0.85)',
        'notebook-lg': '4px 5px 0px 0px rgba(41, 37, 36, 0.9)',
        tape: '0 1px 3px rgba(0,0,0,0.1)',
      },
      animation: {
        'breathe': 'pulse-calm 8s ease-in-out infinite',
      },
      keyframes: {
        'pulse-calm': {
          '0%, 100%': { transform: 'scale(1)', opacity: '0.85' },
          '50%': { transform: 'scale(1.08)', opacity: '0.45' },
        },
      },
    },
  },
  plugins: [],
};
